# Generated by Django 5.0 on 2023-12-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование поверхности')),
                ('description', models.TextField(verbose_name='Описание поверхности')),
                ('width', models.IntegerField(verbose_name='Ширина, м')),
                ('height', models.IntegerField(verbose_name='Высота, м')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес поверхности')),
                ('place', models.CharField(max_length=255, verbose_name='Месторасположение')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='surfaces', verbose_name='Изображение')),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_surface.surface')),
            ],
        ),
    ]
